language: R
cache: packages

addons:
    apt:
        packages:
            - libudunits2-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev

matrix:
    include:
        - os: linux
          r: release
          after_success:
              Rscript -e "covr::codecov(line_exclusions = list('R/areal-stats.R', 'src/clipper.h', 'src/clipper.cpp'))"
        - os: linux
          r: devel
        - os: linux
          r: oldrel
        - os: osx
          r: release
        - os: osx
          r: devel
    allow_failures:
        - os: osx
          r: devel

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
      - covr

