# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_areas
#'
#' layer A layer of polygons
#' @noRd
rcpp_areas <- function(layer) {
    .Call(`_clipper_rcpp_areas`, layer)
}

#' rcpp_path_in_poly
#'
#' @noRd
rcpp_path_in_poly <- function(layer, path_in) {
    .Call(`_clipper_rcpp_path_in_poly`, layer, path_in)
}

